package Model;
// Generated 08/06/2017 20:47:30 by Hibernate Tools 4.3.1



/**
 * Agente generated by hbm2java
 */
public class Agente  implements java.io.Serializable {


     private String cpf;
     private String nome;
     private String senha;

    public Agente() {
    }

	
    public Agente(String cpf) {
        this.cpf = cpf;
    }
    public Agente(String cpf, String nome, String senha) {
       this.cpf = cpf;
       this.nome = nome;
       this.senha = senha;
    }
   
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }




}


