package Model;
// Generated 08/06/2017 15:34:03 by Hibernate Tools 4.3.1



/**
 * AtendimentoDrg generated by hbm2java
 */
public class AtendimentoDrg  implements java.io.Serializable {

//
     private AtendimentoDrgId id;
     private Drg drg;
     private Hospital hospital;
     private short numeroaltas;
     private float taxasmediascobertas;
     private float pagamentosmediostotais;
     private float mediapagamentosmedicare;

    public AtendimentoDrg() {
    }

    public AtendimentoDrg(AtendimentoDrgId id, Drg drg, Hospital hospital, short numeroaltas, float taxasmediascobertas, float pagamentosmediostotais, float mediapagamentosmedicare) {
       this.id = id;
       this.drg = drg;
       this.hospital = hospital;
       this.numeroaltas = numeroaltas;
       this.taxasmediascobertas = taxasmediascobertas;
       this.pagamentosmediostotais = pagamentosmediostotais;
       this.mediapagamentosmedicare = mediapagamentosmedicare;
    }
   
    public AtendimentoDrgId getId() {
        return this.id;
    }
    
    public void setId(AtendimentoDrgId id) {
        this.id = id;
    }
    public Drg getDrg() {
        return this.drg;
    }
    
    public void setDrg(Drg drg) {
        this.drg = drg;
    }
    public Hospital getHospital() {
        return this.hospital;
    }
    
    public void setHospital(Hospital hospital) {
        this.hospital = hospital;
    }
    public short getNumeroaltas() {
        return this.numeroaltas;
    }
    
    public void setNumeroaltas(short numeroaltas) {
        this.numeroaltas = numeroaltas;
    }
    public float getTaxasmediascobertas() {
        return this.taxasmediascobertas;
    }
    
    public void setTaxasmediascobertas(float taxasmediascobertas) {
        this.taxasmediascobertas = taxasmediascobertas;
    }
    public float getPagamentosmediostotais() {
        return this.pagamentosmediostotais;
    }
    
    public void setPagamentosmediostotais(float pagamentosmediostotais) {
        this.pagamentosmediostotais = pagamentosmediostotais;
    }
    public float getMediapagamentosmedicare() {
        return this.mediapagamentosmedicare;
    }
    
    public void setMediapagamentosmedicare(float mediapagamentosmedicare) {
        this.mediapagamentosmedicare = mediapagamentosmedicare;
    }




}


