package Model;
// Generated 01/06/2017 18:13:24 by Hibernate Tools 4.3.1



/**
 * Endereco generated by hbm2java
 */
public class Endereco  implements java.io.Serializable {


     private int idhospital;
     private Hospital hospital;
     private String rua;
     private String cidade;
     private String estado;

    public Endereco() {
    }

    public Endereco(Hospital hospital, String rua, String cidade, String estado) {
       this.hospital = hospital;
       this.rua = rua;
       this.cidade = cidade;
       this.estado = estado;
    }
   
    public int getIdhospital() {
        return this.idhospital;
    }
    
    public void setIdhospital(int idhospital) {
        this.idhospital = idhospital;
    }
    public Hospital getHospital() {
        return this.hospital;
    }
    
    public void setHospital(Hospital hospital) {
        this.hospital = hospital;
    }
    public String getRua() {
        return this.rua;
    }
    
    public void setRua(String rua) {
        this.rua = rua;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


