package Model;
// Generated 08/06/2017 20:47:30 by Hibernate Tools 4.3.1



/**
 * Gerente generated by hbm2java
 */
public class Gerente  implements java.io.Serializable {


     private String cpf;
     private Hospital hospital;
     private String nome;
     private String senha;

    public Gerente() {
    }

	
    public Gerente(String cpf) {
        this.cpf = cpf;
    }
    public Gerente(String cpf, Hospital hospital, String nome, String senha) {
       this.cpf = cpf;
       this.hospital = hospital;
       this.nome = nome;
       this.senha = senha;
    }
   
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public Hospital getHospital() {
        return this.hospital;
    }
    
    public void setHospital(Hospital hospital) {
        this.hospital = hospital;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }




}


