package Model;
// Generated 01/06/2017 18:13:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Hospital generated by hbm2java
 */
public class Hospital  implements java.io.Serializable {


     private int id;
     private String nome;
     private Set atendimentoDrgs = new HashSet(0);
     private Endereco endereco;
     private Set hospitaisRegiaos = new HashSet(0);

    public Hospital() {
    }

	
    public Hospital(int id, String nome) {
        this.id = id;
        this.nome = nome;
    }
    public Hospital(int id, String nome, Set atendimentoDrgs, Endereco endereco, Set hospitaisRegiaos) {
       this.id = id;
       this.nome = nome;
       this.atendimentoDrgs = atendimentoDrgs;
       this.endereco = endereco;
       this.hospitaisRegiaos = hospitaisRegiaos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getAtendimentoDrgs() {
        return this.atendimentoDrgs;
    }
    
    public void setAtendimentoDrgs(Set atendimentoDrgs) {
        this.atendimentoDrgs = atendimentoDrgs;
    }
    public Endereco getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }
    public Set getHospitaisRegiaos() {
        return this.hospitaisRegiaos;
    }
    
    public void setHospitaisRegiaos(Set hospitaisRegiaos) {
        this.hospitaisRegiaos = hospitaisRegiaos;
    }




}


