package Model;
// Generated 08/06/2017 20:47:30 by Hibernate Tools 4.3.1



/**
 * HospitaisRegiaoId generated by hbm2java
 */
public class HospitaisRegiaoId  implements java.io.Serializable {


     private int idhospital;
     private String regiaoReferencia;

    public HospitaisRegiaoId() {
    }

    public HospitaisRegiaoId(int idhospital, String regiaoReferencia) {
       this.idhospital = idhospital;
       this.regiaoReferencia = regiaoReferencia;
    }
   
    public int getIdhospital() {
        return this.idhospital;
    }
    
    public void setIdhospital(int idhospital) {
        this.idhospital = idhospital;
    }
    public String getRegiaoReferencia() {
        return this.regiaoReferencia;
    }
    
    public void setRegiaoReferencia(String regiaoReferencia) {
        this.regiaoReferencia = regiaoReferencia;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HospitaisRegiaoId) ) return false;
		 HospitaisRegiaoId castOther = ( HospitaisRegiaoId ) other; 
         
		 return (this.getIdhospital()==castOther.getIdhospital())
 && ( (this.getRegiaoReferencia()==castOther.getRegiaoReferencia()) || ( this.getRegiaoReferencia()!=null && castOther.getRegiaoReferencia()!=null && this.getRegiaoReferencia().equals(castOther.getRegiaoReferencia()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdhospital();
         result = 37 * result + ( getRegiaoReferencia() == null ? 0 : this.getRegiaoReferencia().hashCode() );
         return result;
   }   


}


