package Model;
// Generated 04/06/2017 22:18:06 by Hibernate Tools 4.3.1



/**
 * HospitaisRegiao generated by hbm2java
 */
public class HospitaisRegiao  implements java.io.Serializable {


     private HospitaisRegiaoId id;
     private Hospital hospital;

    public HospitaisRegiao() {
    }

    public HospitaisRegiao(HospitaisRegiaoId id, Hospital hospital) {
       this.id = id;
       this.hospital = hospital;
    }
   
    public HospitaisRegiaoId getId() {
        return this.id;
    }
    
    public void setId(HospitaisRegiaoId id) {
        this.id = id;
    }
    public Hospital getHospital() {
        return this.hospital;
    }
    
    public void setHospital(Hospital hospital) {
        this.hospital = hospital;
    }




}


